<?php

namespace AppBundle\Repository;

/**
 * LessonPartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LessonPartRepository extends \Doctrine\ORM\EntityRepository
{
}
