# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Category }

    admin.blog_post:
        class: AppBundle\Admin\BlogPostAdmin
        arguments: [~, AppBundle\Entity\BlogPost, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Blog post }
    
    admin.lesson:
        class: AppBundle\Admin\LessonAdmin
        arguments: [~, AppBundle\Entity\Lesson, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Lesson }
            
    admin.lesson_part:
        class: AppBundle\Admin\LessonPartAdmin
        arguments: [~, AppBundle\Entity\LessonPart, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Lesson Part }
            
    admin.attachment:
        class: AppBundle\Admin\AttachmentAdmin
        arguments: [~, AppBundle\Entity\Attachment, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Attachment }
            
    admin.question:
        class: AppBundle\Admin\QuestionAdmin
        arguments: [~, AppBundle\Entity\Question, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Question }
    
    admin.test:
        class: AppBundle\Admin\TestAdmin
        arguments: [~, AppBundle\Entity\Test, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Test }
            
    answer.test:
        class: AppBundle\Admin\AnswerAdmin
        arguments: [~, AppBundle\Entity\Answer, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Answer }